#! /bin/sh
# CERTI bootstrap
# $Id: bootstrap,v 3.0 2002/11/21 01:27:51 breholee Exp $

echo [bootstrapping CERTI `cat VERSION` ...]
set -x
libtoolize --force --copy
aclocal
autoheader
automake --add-missing --copy
autoconf

# $Id: bootstrap,v 3.0 2002/11/21 01:27:51 breholee Exp $
