SET(CTEST_PROJECT_NAME "CERTI")
SET(CTEST_NIGHTLY_START_TIME "00:00:00 EST")

IF(NOT DEFINED CTEST_DROP_METHOD)
  SET(CTEST_DROP_METHOD "http")
ENDIF(NOT DEFINED CTEST_DROP_METHOD)

IF(CTEST_DROP_METHOD STREQUAL "http")
  SET(CTEST_DROP_SITE "www.cdash.org")
  SET(CTEST_DROP_LOCATION "/CDashPublic/submit.php?project=CERTI")
  SET(CTEST_TRIGGER_SITE "")
  set(CTEST_DROP_SITE_CDASH TRUE)
ENDIF(CTEST_DROP_METHOD STREQUAL "http")
