#! /bin/sh
# CERTI myconf
# $Id: myconf,v 3.3 2003/06/27 17:26:28 breholee Exp $

case $1 in
    sun)
	echo Sun Workshop configuration ;
	CC=cc ;
	CXX=CC ;
	AR=CC ;
	CXXFLAGS=" -g " ;
	AR_FLAGS=$CXXFLAGS" -xar -o" ;
	export CC CXX AR CXXFLAGS LDFLAGS AR_FLAGS
	;;

    sun-gcc) 
	echo Sun / gcc configuration ;
	CXXFLAGS=" -Wall " 
	export CXXFLAGS
	;;

    linux) 
	echo GNU/Linux / gcc configuration ;
	;;

    hpux)
        echo HPUX / aCC configuration
	CC=cc ;
        CXX=aCC ;
        export CC CXX
	;;

    hpux-gcc)
        echo HPUX / gcc configuration  
        CC=gcc ;
        CXX=g++ ;
        export CC CXX
	;;
    *)
	echo --- WARNING: Default installation ---
	;;
esac

./configure --prefix=$HOME/CERTI $2 $3 $4 $5

# $Id: myconf,v 3.3 2003/06/27 17:26:28 breholee Exp $
