#

all :
	g++ -g -o Interactive_Federate1516-2010 Interactive_Federate1516-2010.cc \
	-L$(CERTI_HOME)/lib -lRTI1516ed -lCERTId -lFedTime1516ed -DRTI_USES_STD_FSTREAM -std=c++11 \
	-I$(CERTI_HOME)/include/ieee1516-2010 -I$(CERTI_HOME)/include/libhla
	







