
# define a set of string with may-be useful readable name
# this file is meant to be included in a CMakeLists.txt
# not as a standalone CMake script
SET(SPECIFIC_COMPILER_NAME "")
SET(SPECIFIC_SYSTEM_VERSION_NAME "")

IF(WIN32)
# information taken from
# http://www.codeguru.com/cpp/w-p/system/systeminformation/article.php/c8973/
	# Win9x series
	IF(CMAKE_SYSTEM_VERSION MATCHES "4.0")
		SET(SPECIFIC_SYSTEM_VERSION_NAME "Win95")
	ENDIF(CMAKE_SYSTEM_VERSION MATCHES "4.0")
	IF(CMAKE_SYSTEM_VERSION MATCHES "4.10")
		SET(SPECIFIC_SYSTEM_VERSION_NAME "Win98")
	ENDIF(CMAKE_SYSTEM_VERSION MATCHES "4.10")
	IF(CMAKE_SYSTEM_VERSION MATCHES "4.90")
		SET(SPECIFIC_SYSTEM_VERSION_NAME "WinME")
	ENDIF(CMAKE_SYSTEM_VERSION MATCHES "4.90")

	# WinNTyyy series
	IF(CMAKE_SYSTEM_VERSION MATCHES "3.0")
		SET(SPECIFIC_SYSTEM_VERSION_NAME "WinNT351")
	ENDIF(CMAKE_SYSTEM_VERSION MATCHES "3.0")
	IF(CMAKE_SYSTEM_VERSION MATCHES "4.1")
		SET(SPECIFIC_SYSTEM_VERSION_NAME "WinNT4")
	ENDIF(CMAKE_SYSTEM_VERSION MATCHES "4.1")

        # Win2000/XP series
	IF(CMAKE_SYSTEM_VERSION MATCHES "5.0")
		SET(SPECIFIC_SYSTEM_VERSION_NAME "Win2000")
	ENDIF(CMAKE_SYSTEM_VERSION MATCHES "5.0")
	IF(CMAKE_SYSTEM_VERSION MATCHES "5.1")
		SET(SPECIFIC_SYSTEM_VERSION_NAME "WinXP")
	ENDIF(CMAKE_SYSTEM_VERSION MATCHES "5.1")
	IF(CMAKE_SYSTEM_VERSION MATCHES "5.2")
		SET(SPECIFIC_SYSTEM_VERSION_NAME "Win2003")
	ENDIF(CMAKE_SYSTEM_VERSION MATCHES "5.2")

	# WinVista/7 series
	IF(CMAKE_SYSTEM_VERSION MATCHES "6.0")
		SET(SPECIFIC_SYSTEM_VERSION_NAME "WinVISTA")
	ENDIF(CMAKE_SYSTEM_VERSION MATCHES "6.0")
	IF(CMAKE_SYSTEM_VERSION MATCHES "6.1")
		SET(SPECIFIC_SYSTEM_VERSION_NAME "Win7")
	ENDIF(CMAKE_SYSTEM_VERSION MATCHES "6.1")

    # Compilers
	# taken from http://predef.sourceforge.net/precomp.html#sec34
	IF (MSVC)
           IF(MSVC_VERSION EQUAL 1200)
	      SET(SPECIFIC_COMPILER_NAME "MSVC-6.0")
           ENDIF(MSVC_VERSION EQUAL 1200)
           IF(MSVC_VERSION EQUAL 1300)
	      SET(SPECIFIC_COMPILER_NAME "MSVC-7.0")
           ENDIF(MSVC_VERSION EQUAL 1300)
           IF(MSVC_VERSION EQUAL 1310)
	      SET(SPECIFIC_COMPILER_NAME "MSVC-7.1-2003") #Visual Studio 2003
           ENDIF(MSVC_VERSION EQUAL 1310)
           IF(MSVC_VERSION EQUAL 1400)
	      SET(SPECIFIC_COMPILER_NAME "MSVC-8.0-2005") #Visual Studio 2005
           ENDIF(MSVC_VERSION EQUAL 1400)
           IF(MSVC_VERSION EQUAL 1500)
	      SET(SPECIFIC_COMPILER_NAME "MSVC-9.0-2008") #Visual Studio 2008
           ENDIF(MSVC_VERSION EQUAL 1500)
	ENDIF(MSVC)
	IF (MINGW)
	   SET(SPECIFIC_COMPILER_NAME "MinGW")
	ENDIF(MINGW)
	IF (CMAKE_SYSTEM_PROCESSOR MATCHES "x86_64")
       SET(SPECIFIC_SYSTEM_VERSION_NAME "${SPECIFIC_SYSTEM_VERSION_NAME}-x86_64")
	ENDIF(CMAKE_SYSTEM_PROCESSOR MATCHES "x86_64")
ENDIF(WIN32)

IF(UNIX)
  EXECUTE_PROCESS(COMMAND uname -m OUTPUT_VARIABLE MACHINE)
  STRING(REPLACE "\n" "" MACHINE ${MACHINE})
  SET(SPECIFIC_SYSTEM_VERSION_NAME "${CMAKE_SYSTEM_NAME}-${MACHINE}")
  #SET(SPECIFIC_SYSTEM_VERSION_NAME "${SPECIFIC_SYSTEM_VERSION_NAME}-x86_64")
  SET(SPECIFIC_COMPILER_NAME "")
ENDIF(UNIX)
