#!/bin/sh
# $Id: billard-2,v 3.1 2003/02/17 09:17:04 breholee Exp $

# OBJECTCLASS="A:C:D:E:I:P:R:S:T:W:Z:X"
# OBJECTCLASSSET="A:C:D:E:I:P:R:S:T:W:Z:X"
# OBJECTCLASSATTRIBUTE="A:C:D:E:I:P:R:S:T:W:Z:X"
# export OBJECTCLASS
# export OBJECTCLASSSET
# export OBJECTCLASSATTRIBUTE

# RTIA_GCOM="A:C:D:E:I:P:R:S:T:W:Z:X"
# export RTIA_GCOM
# RTIA_GF="A:C:D:E:I:P:R:S:T:W:Z:X"
# export RTIA_GF
# RTIA_GD="A:C:D:E:I:P:R:S:T:W:Z:X"
# export RTIA_GD
# RTIA_GO="A:C:D:E:I:P:R:S:T:W:Z:X"
# export RTIA_GO
# LIBRTI="A:C:D:E:I:P:R:S:T:W:Z:X"
# export LIBRTI
# HERITAGE="A:C:D:E:I:P:R:S:T:W:Z:X"
# export HERITAGE

# #RTIA_GT Z
# RTIA=" A:C:D:E:I:P:R:S:T:W:Z:X"
# export RTIA
# #GAV Z
# #LIBRTI Z
# #HERITAGE I:Z:T
# #SECLEVEL I:E:T
# FEDAMB="A:C:D:E:I:P:R:S:T:W:Z:X"
# export FEDAMB
# MESSAGE="A:C:D:E:I:P:R:S:T:W:Z:X"
# export MESSAGE
# SOCKUN="A:C:D:E:I:P:R:S:T:W:Z:X"
# export SOCKUN

# #DISPLAY=$CERTIDISPLAY
# #export DISPLAY

billard --name 2 --federation Test


