#!/bin/sh

# $Id: billard-init,v 3.0 2002/11/21 01:27:51 breholee Exp $ 

echo "lancement du RTIG"
#cd $CERTIHOME/test/Billard

# CREAD D:E:I:T:R
# CREAD="D:E:I:T:R"
# export CREAD

# FEDERATION E:I:R:S:T:X
# setenv FEDERATION E:I:R:S:T:X
# FEDERATION="A:C:D:E:I:P:R:S:T:W:Z:X"
# export FEDERATION
# FEDAMB="A:C:D:E:I:P:R:S:T:W:Z:X"
# export FEDAMB
# MESSAGE="A:C:D:E:I:P:R:S:T:W:Z:X"
# export MESSAGE
# SOCKUN="A:C:D:E:I:P:R:S:T:W:Z:X"
# export SOCKUN
# RTIA="A:C:D:E:I:P:R:S:T:W:Z:X"
# export RTIA

# GAV E
# setenv GAV E

# # LISTEFEDERATIONS D:E:I:T:X
# #setenv LISTEFEDERATIONS D:E:I:T:X
# LISTEFEDERATIONS="A:C:D:E:I:P:R:S:T:W:Z:X"
# export LISTEFEDERATIONS

# RTIP D:E:I:R:S:T:X:Z
#setenv RTIP E:X
#setenv RTIP D:E:I:R:S:T:X:Z
# RTIP="A:C:D:E:I:P:R:S:T:W:Z:X"
# export RTIP

# #setenv OBJECTCLASS A:C:D:E:I:P:R:S:T:W:Z:X
# #setenv OBJECTCLASSSET A:C:D:E:I:P:R:S:T:W:Z:X
# OBJECTCLASSATTRIBUTE="A:C:D:E:I:P:R:S:T:W:Z:X"
# export OBJECTCLASSATTRIBUTE

rtig
