/* cmdline.h */

/* File autogenerated by gengetopt version 2.10  */

#ifndef CMDLINE_H
#define CMDLINE_H

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef CMDLINE_PARSER_PACKAGE
#define CMDLINE_PARSER_PACKAGE "billard"
#endif

#ifndef CMDLINE_PARSER_VERSION
#define CMDLINE_PARSER_VERSION VERSION
#endif

struct gengetopt_args_info
{
  int auto_arg;	/* auto start.  */
  int coordinated_flag;	/* coordinated time (default=on).  */
  int delay_arg;	/* delay before 1st step.  */
  char * federation_arg;	/* federation name.  */
  char * logfile_arg;	/* file to log events.  */
  char * name_arg;	/* federate name.  */
  char * demo_arg;	/* select demo (static-ddm, dynamic-ddm).  */
  int timer_arg;	/* timer.  */
  int verbose_flag;	/* verbose mode (default=off).  */
  int xoffset_arg;	/* X offset (X11).  */
  int yoffset_arg;	/* Y offset (X11).  */
  int initx_arg;	/* ball initial X value.  */
  int inity_arg;	/* ball initial Y value.  */
  char * filename_arg;  /* FED filename */
  char notimestamp_flag;/* no timestamp (default=off i.e. with timestamp) */

  int help_given ;	/* Whether help was given.  */
  int version_given ;	/* Whether version was given.  */
  int auto_given ;	/* Whether auto was given.  */
  int coordinated_given ;	/* Whether coordinated was given.  */
  int delay_given ;	/* Whether delay was given.  */
  int federation_given ;	/* Whether federation was given.  */
  int logfile_given ;	/* Whether logfile was given.  */
  int name_given ;	/* Whether name was given.  */
  int demo_given ;	/* Whether demo was given.  */
  int timer_given ;	/* Whether timer was given.  */
  int verbose_given ;	/* Whether verbose was given.  */
  int xoffset_given ;	/* Whether xoffset was given.  */
  int yoffset_given ;	/* Whether yoffset was given.  */
  int initx_given ;	/* Whether initx was given.  */
  int inity_given ;	/* Whether inity was given.  */
  int filename_given ; /* Whether FED filename */
  int notimestamp_given ;/* Whether notimestamp given */

} ;

int cmdline_parser (int argc, char * const *argv, struct gengetopt_args_info *args_info);

void cmdline_parser_print_help(void);
void cmdline_parser_print_version(void);

#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* CMDLINE_H */
